### ISSUE TITLE
How to calculate F1 and CCC scores? Are there annotations for testing data to know the accuracy?

### ISSUE THREAD

**Issue by alexmehta** [kuhnkeF/ABAW2020TNT#10]
I finished inference on the model. It outputs a results directory with all the respective csvs. I noticed in the Aff2 dataset, there is no annotations for the testing data. Is there a way for me to calculate accuracy of the testing data or am I stuck with just using the validation and training annotations?

**Comment by kuhnkeF** [comment]
The annotations for the test set are not publicly available. You might contact Dimitrios Kollias to check your results
https://ibug.doc.ic.ac.uk/resources/eccv-2023-4th-abaw/
Please note that Aff-Wild2 has been significantly augmented with more videos and annotations over the last years...
