### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './aff2_processed/video_ts.txt'

### ISSUE THREAD

**Issue by vandana-rajan** [kuhnkeF/ABAW2020TNT#2]
Hi,

I am trying to reproduce your code. 

While running the create_database.py, I got the following error;

_**FileNotFoundError: [Errno 2] No such file or directory: './aff2_processed/video_ts.txt'**_

I noticed that 'video_ts.txt' and 'audio_ts.txt' are not provided. Am I doing something wrong?

Thanks in advance,

**Comment by kuhnkeF** [comment]
These files should be produced by mkvextract. Do you have mkvextract installed on you system? (if not search for mkvtoolnix)

**Comment by vandana-rajan** [comment]
Yeah. Sorry, my bad. Thanks a lot for your reply :)
