### ISSUE TITLE
Alignment data is not matched with the affw2 dataset available in the public site 

### ISSUE THREAD

**Issue by ycyoon** [kuhnkeF/ABAW2020TNT#5]
Hi, I'm trying to run test and validation code.

However, I'm having a trouble to run create_dataset.py

In your code, to use the alignment data, you sort the video files by names and rename the videos in order. What kind of video data types did you use? VA or Expression or AU or All?
I tried with all data set, VA, and Expression but it looks like that the sorting index is not matched with your alignment data and failed to run the test_val_aff2.py

I think the aff2 data provided for competition participants would be different with the dataset which can be download in the "https://ibug.doc.ic.ac.uk/resources/aff-wild2/" site.

Could you upload the code for building alignement data?

**Comment by kuhnkeF** [comment]
We do not plan to release the alignment code. Sadly, the data that was provided to the participants (divided into folders batch1 and batch2) is not in the same structure as the public sets (AU,VA,EXP) on the ABAW website. However,
- You can put all videos into one folder (Overwrite videos with the same name. )
- Replace batch, batch2... in the code to match your folder
- The folder should contain 548 videos

**Comment by kuhnkeF** [comment]
check out the updated code. This should fix all problems with aff2 competition and non competition downloads.
