### ISSUE TITLE
The video names generated based on the video_info.txt has a error.

### ISSUE THREAD

**Issue by Xiao-Yu-Fei** [kuhnkeF/ABAW2020TNT#6]
I put all videos into one folder (Overwrite videos with the same name. ) and the folder contains 548 videos.
but there are some errors like these:

479_AU0__EX1__VA1t.mp4meta.json
479_AU0__EX1__VA1t_alignment_mask.pkl
479_AU1t_EX1t_VA1t.mp4

The first 478 videos is right, but since 479,  the video names generated based on file video_info.txt are not correspond to the alignment_mask.pkl.   so is there a different order between the public data and the competation data?

**Comment by kuhnkeF** [comment]
Please use the updated code. The correct video order is now provided in a file.
