### ISSUE TITLE
Question about the training

### ISSUE THREAD

**Issue by dcafarelli** [kuhnkeF/ABAW2020TNT#7]
Hi, I appreciate your work.

I saw that you reshaped the first layer of your model adding an extra channel input and copying the weights from the "old" layer. 
Then, what about the weight in the last channel?
Did you retrained the whole network or just the first and the last layer?

Thank you very much

**Comment by kuhnkeF** [comment]
Hi,

we fine-tune (train) the whole network during training.
Hope this answers your question.

**Comment by dcafarelli** [comment]
Yes, thank you!
